export const Products = [
  {
    productId: 1,
    productName: "Arctic Apple",
    imageSource: require("../assets/images/products/arctic_apple.jpg"),
    ecoRating: 1.5,
    userRating: 3.2,
    category: "food",
    productPrice: 5.53,
    merchantName: "EcoShop",
  },
  {
    productId: 2,
    productName: "Coconut Oil",
    imageSource: require("../assets/images/products/coconut_oil.jpg"),
    ecoRating: 3.5,
    userRating: 4.1,
    category: "food",
    productPrice: 10.4,
    merchantName: "NatureGoods",
  },
  {
    productId: 3,
    productName: "Granny Smith Apple",
    imageSource: require("../assets/images/products/granny_smith_apple.jpg"),
    ecoRating: 1.5,
    userRating: 3.4,
    category: "food",
    productPrice: 4.19,
    merchantName: "EcoMarketplace",
  },
  {
    productId: 4,
    productName: "Vegan Protein Bar",
    imageSource: require("../assets/images/products/vegan_protein_bar.jpg"),
    ecoRating: 5.0,
    userRating: 4.0,
    category: "food",
    productPrice: 9.97,
    merchantName: "EcoShop",
  },
  {
    productId: 5,
    productName: "Organic Apple",
    imageSource: require("../assets/images/products/organic_apple.jpg"),
    ecoRating: 1.5,
    userRating: 4.5,
    category: "food",
    productPrice: 5.11,
    merchantName: "EcoMarketplace",
  },
  {
    productId: 6,
    productName: "Energy Efficient Washing Machine",
    imageSource: require("../assets/images/products/energy_efficient_washing_machine.jpg"),
    ecoRating: 4.0,
    userRating: 1.9,
    category: "homeAppliances",
    productPrice: 728.74,
    merchantName: "EcoMarketplace",
  },
  {
    productId: 7,
    productName: "Solar Powered Lamp",
    imageSource: require("../assets/images/products/solar_powered_lamp.jpg"),
    ecoRating: 3.9,
    userRating: 3.4,
    category: "homeAppliances",
    productPrice: 32.88,
    merchantName: "SustainableStore",
  },
  {
    productId: 8,
    productName: "Energy Efficient Refrigerator",
    imageSource: require("../assets/images/products/energy_efficient_refrigerator.jpg"),
    ecoRating: 2.8,
    userRating: 4.3,
    category: "homeAppliances",
    productPrice: 734.39,
    merchantName: "GreenMart",
  },
  {
    productId: 9,
    productName: "High Power Refrigerator",
    imageSource: require("../assets/images/products/high_power_refrigerator.jpg"),
    ecoRating: 2.7,
    userRating: 1.2,
    category: "homeAppliances",
    productPrice: 916.6,
    merchantName: "GreenMart",
  },
  {
    productId: 10,
    productName: "Eco-Friendly Refrigerator",
    imageSource: require("../assets/images/products/eco_friendly_refrigerator.jpg"),
    ecoRating: 2.5,
    userRating: 3.5,
    category: "homeAppliances",
    productPrice: 687.54,
    merchantName: "GreenMart",
  },
  {
    productId: 11,
    productName: "Crayola Crayons",
    imageSource: require("../assets/images/products/crayola_crayons.jpg"),
    ecoRating: 1.8,
    userRating: 2.0,
    category: "kids",
    productPrice: 15.28,
    merchantName: "EcoShop",
  },
  {
    productId: 12,
    productName: "Eco-Friendly Puzzle",
    imageSource: require("../assets/images/products/eco_friendly_puzzle.jpg"),
    ecoRating: 3.0,
    userRating: 3.3,
    category: "kids",
    productPrice: 26.35,
    merchantName: "SustainableStore",
  },
  {
    productId: 13,
    productName: "Penguin Jumbo Crayons",
    imageSource: require("../assets/images/products/penguin_jumbo_crayons.jpg"),
    ecoRating: 4.0,
    userRating: 3.6,
    category: "kids",
    productPrice: 30.73,
    merchantName: "NatureGoods",
  },
  {
    productId: 14,
    productName: "Non-Toxic Crayons",
    imageSource: require("../assets/images/products/non_toxic_crayons.jpg"),
    ecoRating: 3.3,
    userRating: 4.1,
    category: "kids",
    productPrice: 39.3,
    merchantName: "EcoShop",
  },
  {
    productId: 15,
    productName: "Organic Cotton Onesie",
    imageSource: require("../assets/images/products/organic_cotton_onesie.jpg"),
    ecoRating: 1.7,
    userRating: 3.0,
    category: "kids",
    productPrice: 68.32,
    merchantName: "GreenMart",
  },
  {
    productId: 16,
    productName: "Corduroy Jeans",
    imageSource: require("../assets/images/products/corduroy_jeans.jpg"),
    ecoRating: 1.2,
    userRating: 3.3,
    category: "mensFashion",
    productPrice: 31.48,
    merchantName: "EcoMarketplace",
  },
  {
    productId: 17,
    productName: "Organic Cotton T-Shirt",
    imageSource: require("../assets/images/products/organic_cotton_t_shirt.jpg"),
    ecoRating: 2.9,
    userRating: 3.6,
    category: "mensFashion",
    productPrice: 19.61,
    merchantName: "SustainableStore",
  },
  {
    productId: 18,
    productName: "Recycled Plastic Belt",
    imageSource: require("../assets/images/products/recycled_plastic_belt.jpg"),
    ecoRating: 3.5,
    userRating: 3.1,
    category: "mensFashion",
    productPrice: 30.52,
    merchantName: "GreenMart",
  },
  {
    productId: 19,
    productName: "Organic Cotton Jeans",
    imageSource: require("../assets/images/products/organic_cotton_jeans.jpg"),
    ecoRating: 2.4,
    userRating: 1.2,
    category: "mensFashion",
    productPrice: 34.54,
    merchantName: "EcoMarketplace",
  },
  {
    productId: 20,
    productName: "Denim Jeans",
    imageSource: require("../assets/images/products/denim_jeans.jpg"),
    ecoRating: 4.8,
    userRating: 3.0,
    category: "mensFashion",
    productPrice: 49.18,
    merchantName: "SustainableStore",
  },
  {
    productId: 21,
    productName: "Eco-Friendly Necklace",
    imageSource: require("../assets/images/products/eco_friendly_necklace.jpg"),
    ecoRating: 1.4,
    userRating: 2.9,
    category: "womensFashion",
    productPrice: 40.28,
    merchantName: "GreenMart",
  },
  {
    productId: 22,
    productName: "Polyester Handbag",
    imageSource: require("../assets/images/products/polyester_handbag.jpg"),
    ecoRating: 1.6,
    userRating: 2.4,
    category: "womensFashion",
    productPrice: 88.87,
    merchantName: "SustainableStore",
  },
  {
    productId: 23,
    productName: "Cotton Handbag",
    imageSource: require("../assets/images/products/cotton_handbag.jpg"),
    ecoRating: 2.6,
    userRating: 2.2,
    category: "womensFashion",
    productPrice: 12.82,
    merchantName: "EcoShop",
  },
  {
    productId: 24,
    productName: "Hemp Scarf",
    imageSource: require("../assets/images/products/hemp_scarf.jpg"),
    ecoRating: 4.7,
    userRating: 5.0,
    category: "womensFashion",
    productPrice: 48.4,
    merchantName: "NatureGoods",
  },
  {
    productId: 25,
    productName: "Gucci Handbag",
    imageSource: require("../assets/images/products/gucci_handbag.jpg"),
    ecoRating: 3.6,
    userRating: 2.2,
    category: "womensFashion",
    productPrice: 153.38,
    merchantName: "EcoMarketplace",
  },
];

export default Products;
