const cart = [
  {
    productId: 22,
    productName: "Polyester Handbag",
    imageSource: require("../assets/images/products/polyester_handbag.jpg"),
    ecoRating: 1.6,
    userRating: 2.4,
    category: "womensFashion",
    productPrice: 88.87,
    merchantName: "Store A",
    orderStatus: "toShip",
  },
  {
    productId: 23,
    productName: "Cotton Handbag",
    imageSource: require("../assets/images/products/cotton_handbag.jpg"),
    ecoRating: 2.6,
    userRating: 2.2,
    category: "womensFashion",
    productPrice: 12.82,
    merchantName: "Store A",
    orderStatus: "toReceive",
  },
  {
    productId: 24,
    productName: "Hemp Scarf",
    imageSource: require("../assets/images/products/hemp_scarf.jpg"),
    ecoRating: 4.7,
    userRating: 5.0,
    category: "womensFashion",
    productPrice: 48.4,
    merchantName: "Store B",
    orderStatus: "toReceive",
  },
  {
    productId: 25,
    productName: "Gucci Handbag",
    imageSource: require("../assets/images/products/gucci_handbag.jpg"),
    ecoRating: 3.6,
    userRating: 2.2,
    category: "womensFashion",
    productPrice: 153.38,
    merchantName: "Store C",
    orderStatus: "toShip",
  },
  {
    productId: 11,
    productName: "Crayola Crayons",
    imageSource: require("../assets/images/products/crayola_crayons.jpg"),
    ecoRating: 1.8,
    userRating: 2.0,
    category: "kids",
    productPrice: 15.28,
    merchantName: "EcoKids",
    orderStatus: "toShip",
  },
  {
    productId: 12,
    productName: "Eco-Friendly Puzzle",
    imageSource: require("../assets/images/products/eco_friendly_puzzle.jpg"),
    ecoRating: 3.0,
    userRating: 3.3,
    category: "kids",
    productPrice: 26.35,
    merchantName: "EcoKids",
    orderStatus: "toShip",
  },
  {
    productId: 7,
    productName: "Solar Powered Lamp",
    imageSource: require("../assets/images/products/solar_powered_lamp.jpg"),
    ecoRating: 3.9,
    userRating: 3.4,
    category: "homeAppliances",
    productPrice: 32.88,
    merchantName: "SustainableStore",
    orderStatus: "completed",
  },
  {
    productId: 8,
    productName: "Energy Efficient Refrigerator",
    imageSource: require("../assets/images/products/energy_efficient_refrigerator.jpg"),
    ecoRating: 2.8,
    userRating: 4.3,
    category: "homeAppliances",
    productPrice: 734.39,
    merchantName: "GreenMart",
    orderStatus: "completed",
  },
];

export default cart;
